---
title: "Untitled"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## 한국 지도 시각화

```{r}
# Kormaps를 이용해 세부적인 한국 지도 그리기
# 패키지 세팅하기
if (!require("Kormaps")){devtools::install_github("cardiomoon/Kormaps")}
if (!require("tmap")){install.packages("tmap")}
if (!require("cartogram")){devtools::install_github("sjewo/cartogram")}
if (!require("mapproj")){install.packages("mapproj")}
library(Kormaps)
library(tmap)
library(cartogram)

```
```{r}

# 윈도우를 위한 폰트 설정하기
# for windows
windowsFonts()
if (!require("extrafont")){install.packages("extrafont")}
library(extrafont)
#font_import()
head(loadfonts())

```

```{r}
# 내장 인구 데이터를 이용해 한국 지도 그리기
qtm(kormap1)
#qtm(korpopmap1,"총인구_명")
#qtm(korpopmap2,"총인구_명")
```
```{r}
# 인코딩 문제 고치기
Encoding(names(korpopmap1))<-"UTF-8"
Encoding(korpopmap1@data$name)<-"UTF-8"
Encoding(korpopmap1@data$`행정구역별_읍면동`)<-"UTF-8"

head(korpopmap1@data)

```
```{r}
library(tidyverse)

# ggplot 으로 한국 지도 그리기 위한 전처리
kor <- fortify(korpopmap1, region = "id")
kordf <- merge(kor, korpopmap1@data, by = "id")

```
```{r}

# ggplot으로 한국 지도 그리기
ggplot(kordf, aes(x=long.x, y=lat.x, group=group.x, fill=`총인구_명`)) + 
  geom_polygon(color="black") + coord_map() +
  scale_fill_gradient(high = "#132B43", low = "#56B1F7") +
  theme(title=element_text(family="NanumGothic",face="bold"))

# ggplot facet 기능 적용해 보기
# 남녀 인구로 구분
kordfs <- kordf %>% select(id:`여자_명`) %>%
  gather(`성별`,`인구`,-(id:`총인구_명`))

# 남녀 인구 한국 지도 시각화
ggplot(kordfs, aes(x=long.x, y=lat.x, group=group.x, fill=`인구`)) + 
  geom_polygon(color="black") + coord_map() +
  scale_fill_gradient(high = "#132B43", low = "#56B1F7") +
  theme(text=element_text(family="NanumGothic",face="bold")) +
  facet_grid(.~ `성별`)


```

## 2016년 총선 결과 cartogram 그리기
<https://www.facebook.com/groups/krstudy/permalink/785465478294393/>

## cartogram의 다른 예시(ggplot 아님)
<https://github.com/jjangkr/cartogram_4_anything>

```{r}
if (!require("rgdal")){install.packages("rgdal")}
if (!require("maptools")){install.packages("maptools")}
library(rgdal)
library(maptools)
korea <- readOGR(dsn = "./data/election", layer="DistResult2016", encoding = 'euc-kr')

# sp패키지의 SpatialPolygonsDataFrame 자료형을 사용합니다.
class(korea)
# 카토그램 모양을 계산합니다. 시간이 꽤 걸리니 5이하의 숫자를 사옹해 주세요.
# 지금은 미리 만든 객체를 불러올 것입니다.
# c_korea <- cartogram(korea, "Pop", 5)
# save(c_korea,file = "c_korea.RData")
load("c_korea.RData")
# data.frame으로 변환하기 위해 fortify 함수를 사용합니다.
c_korea.df <- fortify(c_korea)
# 변환된 상태
class(c_korea.df)
head(c_korea.df)
summary(c_korea.df)
str(c_korea.df)
# 데이터를 합치기 위한 키 생성
c_korea@data$id <- rownames(c_korea@data)
# 데이터 합치기 - 조인
c_korea.df <- c_korea.df %>% left_join(c_korea@data, by="id")
str(c_korea.df)
# 인코딩 수정
Encoding(c_korea.df$Dist)<-"UTF-8"
Encoding(c_korea.df$SD)<-"UTF-8"
Encoding(c_korea.df$SGG)<-"UTF-8"
str(c_korea.df)

# 빈 테마 미리 만들기
theme_clean <- function(base_size = 12) {
  require(grid)
  theme_grey(base_size) %+replace%
    theme(
      axis.title = element_blank(),
      axis.text = element_blank(),
      panel.background = element_blank(),
      panel.grid = element_blank(),
      axis.ticks.length = unit(0, "cm"),
      complete = TRUE
    )
}

# 카토그램 그리기 
election <- ggplot(c_korea.df, aes(x=long, y=lat, group=group)) + 
  geom_polygon(aes(alpha=RatioS), fill=rgb(1,0,0), colour="white", lwd = 0.01) +
  geom_polygon(aes(alpha=RatioP), fill=rgb(0,1,0), colour="white", lwd = 0.01) +
  geom_polygon(aes(alpha=RatioT), fill=rgb(0,0,1), colour="white", lwd = 0.01) +
  guides(fill=FALSE, alpha=FALSE) + theme_clean() + coord_map()

election

```
