install.packages("nycflights13")
library(readr)
library(DBI)
library(RSQLite)
head(nycflights13::airlines)
head(nycflights13::airports)
head(nycflights13::flights)
head(nycflights13::planes)
head(nycflights13::weather)
seul <- dbConnect(RSQLite::SQLite(), dbname="sql_seulgi.db")
dbListTables(seul)
dbWriteTable(seul, "airlines", nycflights13::airlines, overwrite=T)  
dbWriteTable(seul, "airports", nycflights13::airports, overwrite=T)  
dbWriteTable(seul, "flights", nycflights13::flights, overwrite=T)  
dbWriteTable(seul, "planes", nycflights13::planes, overwrite=T)  
dbWriteTable(seul, "weather", nycflights13::weather, overwrite=T)  
dbListTables(seul)  
